/**
 * Cuisines for the composer's picker.
 *
 * Adjectival, not place names: a recipe's cuisine is "Italian", not "Italy".
 * Every country is here, plus the regional and sub-national cuisines people
 * actually write on recipes — "Sicilian" and "Cajun" and "Tex-Mex" are answers
 * a free-text field used to allow and a country list alone would lose.
 *
 * COMMON floats the two dozen most-written to the top of an unsearched list,
 * because scrolling 200 entries to reach "Italian" is worse than typing it was.
 */

/** Shown first when nothing has been typed. */
export const COMMON_CUISINES: string[] = [
  'Italian',
  'Mexican',
  'Japanese',
  'Chinese',
  'Indian',
  'Thai',
  'French',
  'Greek',
  'Spanish',
  'Korean',
  'Vietnamese',
  'American',
  'Mediterranean',
  'Middle Eastern',
  'Turkish',
  'Lebanese',
  'Moroccan',
  'Ethiopian',
  'Brazilian',
  'Peruvian',
  'German',
  'British',
  'Portuguese',
  'Polish',
  'Filipino',
];

/** Every cuisine the picker offers, alphabetically. */
export const ALL_CUISINES: string[] = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Anatolian',
  'Andean',
  'Andorran',
  'Anglo-Indian',
  'Angolan',
  'Argentine',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Balkan',
  'Bangladeshi',
  'Barbadian',
  'Basque',
  'Bavarian',
  'Belarusian',
  'Belgian',
  'Belizean',
  'Bengali',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian',
  'Botswanan',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinabe',
  'Burmese',
  'Burundian',
  'Cajun',
  'Californian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cantonese',
  'Cape Verdean',
  'Caribbean',
  'Catalan',
  'Central Asian',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comorian',
  'Congolese',
  'Costa Rican',
  'Creole',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djiboutian',
  'Dominican',
  'Dutch',
  'East African',
  'East Timorese',
  'Ecuadorian',
  'Egyptian',
  'Emirati',
  'English',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'Fusion',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Goan',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinean',
  'Gujarati',
  'Guyanese',
  'Haitian',
  'Honduran',
  'Hunan',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakh',
  'Kenyan',
  'Kerala',
  'Kittitian',
  'Korean',
  'Kosovar',
  'Kurdish',
  'Kuwaiti',
  'Kyrgyz',
  'Lao',
  'Latin American',
  'Latvian',
  'Lebanese',
  'Levantine',
  'Liberian',
  'Libyan',
  'Liechtenstein',
  'Lithuanian',
  'Luxembourgish',
  'Macedonian',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Mauritanian',
  'Mauritian',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Moldovan',
  'Monacan',
  'Mongolian',
  'Montenegrin',
  'Moroccan',
  'Mozambican',
  'Namibian',
  'Nepalese',
  'New Zealand',
  'Nicaraguan',
  'Nigerian',
  'Nigerien',
  'Nikkei',
  'Nordic',
  'North African',
  'North Korean',
  'Norwegian',
  'Oaxacan',
  'Omani',
  'Pacific Islander',
  'Pakistani',
  'Palauan',
  'Palestinian',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Persian',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Provencal',
  'Punjabi',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Salvadoran',
  'Samoan',
  'Saudi',
  'Scandinavian',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Shanghainese',
  'Sichuan',
  'Sicilian',
  'Sierra Leonean',
  'Singaporean',
  'Slovak',
  'Slovenian',
  'Somali',
  'South African',
  'South Asian',
  'South Korean',
  'Southeast Asian',
  'Southern',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamese',
  'Swazi',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tanzanian',
  'Tex-Mex',
  'Thai',
  'Togolese',
  'Tongan',
  'Trinidadian',
  'Tunisian',
  'Turkish',
  'Turkmen',
  'Tuscan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbek',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'West African',
  'Yemeni',
  'Yucatecan',
  'Zambian',
  'Zimbabwean',
];

/**
 * Ranks matches so a prefix beats a match in the middle: typing "ind" should
 * put Indian above Anglo-Indian.
 */
export function searchCuisines(query: string): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return COMMON_CUISINES;
  const hits = ALL_CUISINES.filter((c) => c.toLowerCase().includes(q));
  return hits.sort((a, b) => {
    const ap = a.toLowerCase().startsWith(q) ? 0 : 1;
    const bp = b.toLowerCase().startsWith(q) ? 0 : 1;
    return ap - bp || a.localeCompare(b);
  });
}
