-- Launch taxonomy: categories (§6/§9), tag vocabulary (§19.2), canonical
-- ingredients (§22), and the MenuMatch-operated seed creator accounts (§5.3).

insert into public.categories (slug, label, description, position, feed_kind, filter_tag, max_total_minutes, min_protein_g) values
  ('for_you',     'For You',      'Picked from what you save and skip',      0,  'for_you',         null,           null, null),
  ('following',   'Following',    'New from creators you follow',            1,  'following',       null,           null, null),
  ('dinner',      'Dinner',       'Mains for the end of the day',            2,  'tag_filtered',    null,           null, null),
  ('lunch',       'Lunch',        'Midday plates and bowls',                 3,  'tag_filtered',    null,           null, null),
  ('breakfast',   'Breakfast',    'Mornings, fast and slow',                 4,  'tag_filtered',    null,           null, null),
  ('snacks',      'Snacks',       'Small things worth making',               5,  'tag_filtered',    null,           null, null),
  ('dessert',     'Dessert',      'Sweet finishes',                          6,  'tag_filtered',    null,           null, null),
  ('drinks',      'Drinks',       'Non-alcoholic by default',                7,  'tag_filtered',    null,           null, null),
  ('quick',       'Quick',        'On the table in half an hour',            8,  'time_capped',     null,           30,   null),
  ('high_protein','High Protein', 'Recipes with protein data provided',      9,  'nutrition_gated', null,           null, 25),
  ('vegetarian',  'Vegetarian',   'No meat, creator-tagged',                 10, 'tag_filtered',    'vegetarian',   null, null);

insert into public.tags (name, slug, type, is_verified_type) values
  ('Vegetarian','vegetarian','dietary',false), ('Vegan','vegan','dietary',false),
  ('Gluten-free','gluten-free','dietary',false), ('Dairy-free','dairy-free','dietary',false),
  ('High protein','high-protein','dietary',false), ('Low carb','low-carb','dietary',false),
  ('Italian','italian','cuisine',false), ('Mexican','mexican','cuisine',false),
  ('Japanese','japanese','cuisine',false), ('Indian','indian','cuisine',false),
  ('Mediterranean','mediterranean','cuisine',false), ('Thai','thai','cuisine',false),
  ('American','american','cuisine',false), ('Korean','korean','cuisine',false),
  ('French','french','cuisine',false), ('Middle Eastern','middle-eastern','cuisine',false),
  ('British','british','cuisine',false), ('Chinese','chinese','cuisine',false),
  ('Dinner','dinner','meal',false), ('Lunch','lunch','meal',false),
  ('Breakfast','breakfast','meal',false), ('Snack','snack','meal',false),
  ('Dessert','dessert','meal',false), ('Drink','drink','meal',false),
  ('Sheet pan','sheet-pan','equipment',false), ('One pot','one-pot','equipment',false),
  ('No cook','no-cook','equipment',false), ('Blender','blender','equipment',false),
  ('Air fryer','air-fryer','equipment',false), ('Slow cooker','slow-cooker','equipment',false),
  ('Weeknight','weeknight','occasion',false), ('Meal prep','meal-prep','occasion',false),
  ('Batch cooking','batch-cooking','occasion',false), ('Company worthy','company-worthy','occasion',false),
  -- §19.2 standard allergen set. Never auto-derived from ingredient text.
  ('Milk','allergen-milk','allergen',true), ('Eggs','allergen-eggs','allergen',true),
  ('Fish','allergen-fish','allergen',true), ('Shellfish','allergen-shellfish','allergen',true),
  ('Tree nuts','allergen-tree-nuts','allergen',true), ('Peanuts','allergen-peanuts','allergen',true),
  ('Wheat','allergen-wheat','allergen',true), ('Soy','allergen-soy','allergen',true),
  ('Sesame','allergen-sesame','allergen',true);

insert into public.ingredients (canonical_name, aliases, category, protein_group) values
  ('chicken thigh', array['chicken thighs','bone-in chicken thighs','boneless chicken thighs'], 'poultry', 'chicken'),
  ('chicken breast', array['chicken breasts','boneless chicken breast'], 'poultry', 'chicken'),
  ('ground beef', array['beef mince','minced beef'], 'meat', 'beef'),
  ('beef chuck', array['stewing beef','chuck roast'], 'meat', 'beef'),
  ('pork shoulder', array['pork butt','boston butt'], 'meat', 'pork'),
  ('bacon', array['streaky bacon'], 'meat', 'pork'),
  ('salmon fillet', array['salmon','salmon fillets'], 'seafood', 'fish'),
  ('white fish fillet', array['cod','haddock','pollock'], 'seafood', 'fish'),
  ('prawns', array['shrimp','king prawns'], 'seafood', 'shellfish'),
  ('eggs', array['egg','large eggs'], 'dairy', 'egg'),
  ('firm tofu', array['tofu','extra firm tofu'], 'plant protein', 'tofu'),
  ('chickpeas', array['garbanzo beans','canned chickpeas'], 'legume', 'legume'),
  ('black beans', array['canned black beans'], 'legume', 'legume'),
  ('red lentils', array['split red lentils','masoor dal'], 'legume', 'legume'),
  ('halloumi', array['grilling cheese'], 'dairy', 'cheese'),
  ('paneer', array[]::text[], 'dairy', 'cheese'),
  ('greek yogurt', array['yoghurt','plain yogurt'], 'dairy', null),
  ('parmesan', array['parmigiano reggiano','pecorino'], 'dairy', null),
  ('mozzarella', array['fresh mozzarella'], 'dairy', null),
  ('feta', array[]::text[], 'dairy', null),
  ('olive oil', array['extra virgin olive oil'], 'pantry', null),
  ('garlic', array['garlic cloves'], 'aromatic', null),
  ('onion', array['yellow onion','brown onion'], 'aromatic', null),
  ('shallot', array['shallots'], 'aromatic', null),
  ('ginger', array['fresh ginger'], 'aromatic', null),
  ('lemon', array['lemons'], 'produce', null),
  ('lime', array['limes'], 'produce', null),
  ('tomatoes', array['tomato','cherry tomatoes','plum tomatoes'], 'produce', null),
  ('canned tomatoes', array['chopped tomatoes','crushed tomatoes'], 'pantry', null),
  ('spinach', array['baby spinach'], 'produce', null),
  ('broccoli', array['tenderstem broccoli','broccolini'], 'produce', null),
  ('cauliflower', array[]::text[], 'produce', null),
  ('sweet potato', array['sweet potatoes'], 'produce', null),
  ('potato', array['potatoes','floury potatoes'], 'produce', null),
  ('mushrooms', array['chestnut mushrooms','cremini'], 'produce', null),
  ('courgette', array['zucchini'], 'produce', null),
  ('aubergine', array['eggplant'], 'produce', null),
  ('red pepper', array['bell pepper','red bell pepper'], 'produce', null),
  ('cucumber', array[]::text[], 'produce', null),
  ('avocado', array['avocados'], 'produce', null),
  ('spring onion', array['scallions','green onions'], 'produce', null),
  ('coriander', array['cilantro','fresh coriander'], 'herb', null),
  ('parsley', array['flat leaf parsley'], 'herb', null),
  ('basil', array['fresh basil'], 'herb', null),
  ('mint', array['fresh mint'], 'herb', null),
  ('rice', array['long grain rice','basmati rice','jasmine rice'], 'grain', null),
  ('pasta', array['spaghetti','penne','rigatoni'], 'grain', null),
  ('noodles', array['rice noodles','egg noodles','udon'], 'grain', null),
  ('bread', array['sourdough','crusty bread'], 'grain', null),
  ('tortillas', array['corn tortillas','flour tortillas'], 'grain', null),
  ('rolled oats', array['oats','porridge oats'], 'grain', null),
  ('plain flour', array['all-purpose flour'], 'baking', null),
  ('butter', array['unsalted butter'], 'dairy', null),
  ('sugar', array['caster sugar','granulated sugar'], 'baking', null),
  ('brown sugar', array['light brown sugar'], 'baking', null),
  ('dark chocolate', array['chocolate','70% chocolate'], 'baking', null),
  ('peanut butter', array[]::text[], 'pantry', null),
  ('tahini', array[]::text[], 'pantry', null),
  ('soy sauce', array['light soy sauce'], 'pantry', null),
  ('fish sauce', array[]::text[], 'pantry', null),
  ('coconut milk', array['full fat coconut milk'], 'pantry', null),
  ('curry paste', array['thai red curry paste','green curry paste'], 'pantry', null),
  ('gochujang', array['korean chilli paste'], 'pantry', null),
  ('harissa', array['rose harissa'], 'pantry', null),
  ('cumin', array['ground cumin'], 'spice', null),
  ('smoked paprika', array['paprika'], 'spice', null),
  ('chilli flakes', array['red pepper flakes'], 'spice', null),
  ('honey', array[]::text[], 'pantry', null),
  ('maple syrup', array[]::text[], 'pantry', null),
  ('vanilla extract', array[]::text[], 'baking', null),
  ('frozen berries', array['mixed berries','blueberries'], 'produce', null),
  ('banana', array['bananas'], 'produce', null),
  ('almond milk', array['oat milk','plant milk'], 'dairy alternative', null),
  ('cocoa powder', array[]::text[], 'baking', null);

-- §5.3: company-operated accounts are visibly labeled as such in the client.
insert into public.users (username, display_name, bio, is_creator, is_seed_account) values
  ('menumatch.kitchen','MenuMatch Kitchen','Recipes developed and tested in house.',true,true),
  ('sofia.reyes','Sofia Reyes','Weeknight cooking, mostly one pan.',true,true),
  ('tomas.lindqvist','Tomas Lindqvist','Baking and slow Sundays.',true,true),
  ('amara.okafor','Amara Okafor','Big flavours, short ingredient lists.',true,true),
  ('kenji.watanabe','Kenji Watanabe','Rice, noodles, and things on top of them.',true,true),
  ('priya.nair','Priya Nair','Vegetarian cooking from a South Indian kitchen.',true,true),
  ('luca.bianchi','Luca Bianchi','Pasta, and the sauces that earn it.',true,true),
  ('noor.haddad','Noor Haddad','Mezze, grains, and a lot of lemon.',true,true);
